import json

cells = []

# ===== CELL 1: Setup =====
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ===== CELL 1: Setup & Install =====\n",
        "!pip install -q transformers accelerate datasets huggingface_hub joblib scipy tqdm\n",
        "!git clone https://github.com/ANLPproject/LinguaFranca.git /kaggle/working/LinguaFranca\n",
        "\n",
        "import os, sys\n",
        "os.environ['HF_HUB_DISABLE_SYMLINKS_WARNING'] = '1'\n",
        "\n",
        "from huggingface_hub import login\n",
        "try:\n",
        "    from kaggle_secrets import UserSecretsClient\n",
        "    login(token=UserSecretsClient().get_secret('HF_TOKEN'))\n",
        "except Exception as e:\n",
        "    print(f'Kaggle Secrets failed ({e}), using fallback...')\n",
        "    login(token='hf_placeholder')  # replace if needed\n"
    ]
})

# ===== CELL 2: Retrain probes with the fix =====
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ===== CELL 2: Download hidden states from HF, retrain probes with the hop_idx fix =====\n",
        "# This does NOT need a GPU. It downloads the .pt hidden state files from HF,\n",
        "# trains a simple LogisticRegression with the CORRECT hop_idx == 0 filter,\n",
        "# and uploads the fixed probes back to HF.\n",
        "\n",
        "from huggingface_hub import snapshot_download, HfApi, hf_hub_download\n",
        "from pathlib import Path\n",
        "import json, torch, numpy as np, joblib\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "from sklearn.pipeline import make_pipeline\n",
        "from sklearn.model_selection import GroupShuffleSplit\n",
        "\n",
        "REPO = 'AnishRacherla/LinguaFranca-Phase3'\n",
        "\n",
        "# Download hidden states and labels\n",
        "print('Downloading hidden states from HF (this may take a few minutes)...')\n",
        "hs_local = Path(snapshot_download(REPO, repo_type='dataset', allow_patterns='data/hidden_states/*'))\n",
        "hs_dir = hs_local / 'data' / 'hidden_states'\n",
        "\n",
        "labels_path = hf_hub_download(REPO, 'data/2wikimultihopqa/augmented.jsonl', repo_type='dataset')\n",
        "with open(labels_path, encoding='utf-8') as f:\n",
        "    examples = [json.loads(l) for l in f]\n",
        "\n",
        "valid_ex = [ex for ex in examples if (hs_dir / f\"{ex['id']}.pt\").exists()]\n",
        "print(f'Found {len(valid_ex)} examples with hidden states')\n",
        "\n",
        "# GroupShuffleSplit (same as advanced_probing.py)\n",
        "groups = [ex.get('clean_pair_id', ex['id']) for ex in valid_ex]\n",
        "gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)\n",
        "train_idx, test_idx = next(gss.split(valid_ex, groups=groups))\n",
        "train_ex = [valid_ex[i] for i in train_idx]\n",
        "test_ex = [valid_ex[i] for i in test_idx]\n",
        "\n",
        "# Get layer indices from a sample file\n",
        "sample = torch.load(hs_dir / f\"{valid_ex[0]['id']}.pt\", weights_only=False)\n",
        "layer_indices = sample.get('layer_indices', list(range(sample['pooled'].shape[0])))\n",
        "print(f'Layer indices: {layer_indices}')\n",
        "\n",
        "def extract_hop1_data(ex_list, hs_dir, layer_idx):\n",
        "    X, y = [], []\n",
        "    for ex in ex_list:\n",
        "        pt_path = hs_dir / f\"{ex['id']}.pt\"\n",
        "        if not pt_path.exists(): continue\n",
        "        data = torch.load(pt_path, weights_only=False)\n",
        "        pooled = data['pooled']\n",
        "        for hop in ex.get('hops', []):\n",
        "            h_idx = hop['hop_idx'] - 1  # hop 1 -> index 0\n",
        "            if h_idx != 0: continue      # *** THE FIX: only hop 1 ***\n",
        "            if hop.get('label') in (0, 1) and h_idx < pooled.shape[1]:\n",
        "                X.append(pooled[layer_idx, h_idx].detach().numpy())\n",
        "                y.append(hop['label'])\n",
        "    return np.array(X), np.array(y)\n",
        "\n",
        "# Train and save probes for all layers\n",
        "probe_dir = Path('/kaggle/working/fixed_probes')\n",
        "probe_dir.mkdir(exist_ok=True)\n",
        "\n",
        "print('Training fixed hop-1 probes...')\n",
        "for li in layer_indices:\n",
        "    X_tr, y_tr = extract_hop1_data(train_ex, hs_dir, layer_idx=li)\n",
        "    if len(y_tr) > 0:\n",
        "        clf = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42))\n",
        "        clf.fit(X_tr, y_tr)\n",
        "        joblib.dump(clf, probe_dir / f'hop1_probe_layer{li}.joblib')\n",
        "        # Quick sanity: accuracy on train\n",
        "        acc = (clf.predict(X_tr) == y_tr).mean()\n",
        "        print(f'  Layer {li:>2}: trained on {len(y_tr)} hop-1 samples, train acc = {acc:.3f}')\n",
        "\n",
        "# Save train IDs\n",
        "json.dump([ex['id'] for ex in train_ex], open(probe_dir / 'probe_train_ids.json', 'w'))\n",
        "print(f'Saved {len(layer_indices)} fixed probes + probe_train_ids.json to {probe_dir}')\n",
        "\n",
        "# Upload to HF\n",
        "print('Uploading fixed probes to HuggingFace...')\n",
        "api = HfApi()\n",
        "for f in probe_dir.iterdir():\n",
        "    api.upload_file(\n",
        "        path_or_fileobj=str(f),\n",
        "        path_in_repo=f'probes/{f.name}',\n",
        "        repo_id=REPO,\n",
        "        repo_type='dataset'\n",
        "    )\n",
        "    print(f'  Uploaded probes/{f.name}')\n",
        "print('Done! Fixed probes are now on HuggingFace.')\n"
    ]
})

# ===== CELL 3: Load model =====
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ===== CELL 3: Load model =====\n",
        "import torch\n",
        "from transformers import AutoModelForCausalLM, AutoTokenizer\n",
        "\n",
        "MODEL = 'meta-llama/Llama-3.2-3B-Instruct'\n",
        "print('Loading model...')\n",
        "tokenizer = AutoTokenizer.from_pretrained(MODEL)\n",
        "model = AutoModelForCausalLM.from_pretrained(MODEL, dtype=torch.float16, device_map='auto')\n",
        "model.eval()\n",
        "print(f'Model loaded. Device: {model.device}')\n"
    ]
})

# ===== CELL 4: Load dataset & build pairs =====
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ===== CELL 4: Download dataset & build minimal pairs =====\n",
        "import json\n",
        "from huggingface_hub import hf_hub_download\n",
        "\n",
        "print('Downloading dataset...')\n",
        "data_path = hf_hub_download('AnishRacherla/LinguaFranca-Phase3',\n",
        "                            'data/2wikimultihopqa/augmented.jsonl', repo_type='dataset')\n",
        "with open(data_path, encoding='utf-8') as f:\n",
        "    data = [json.loads(line) for line in f]\n",
        "\n",
        "clean_map = {d['id']: d for d in data if not d.get('is_counterfactual', False)}\n",
        "cfs = [d for d in data if d.get('is_counterfactual', False)]\n",
        "print(f'Loaded {len(clean_map)} clean examples, {len(cfs)} counterfactuals.')\n",
        "\n",
        "pairs = []\n",
        "for cf in cfs:\n",
        "    clean = clean_map.get(cf.get('clean_pair_id'))\n",
        "    if not clean: continue\n",
        "    c_h1 = next((h for h in clean.get('hops', []) if h['hop_idx'] == 1), None)\n",
        "    f_h1 = next((h for h in cf.get('hops', []) if h['hop_idx'] == 1), None)\n",
        "    if c_h1 and f_h1 and c_h1.get('label') == 0 and f_h1.get('label') == 1:\n",
        "        pairs.append((clean, cf))\n",
        "print(f'Found {len(pairs)} perfect minimal pairs.')\n"
    ]
})

# ===== CELL 5: Extract features (GPU, ~1 hour) =====
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ===== CELL 5: Extract hop-1 probe features under causal patching (needs the model, NOT the probes) =====\n",
        "# Saves everything to probe_features.npz so any probe can be scored in CELL 6 in seconds.\n",
        "\n",
        "import re, difflib, json\n",
        "import numpy as np\n",
        "import torch\n",
        "import torch.nn.functional as F\n",
        "from tqdm.auto import tqdm\n",
        "\n",
        "FEATURE_LAYERS = [9, 10, 11, 12, 13]\n",
        "MIN_GAP = 1.0\n",
        "BATCH = 3\n",
        "CONTROL_LAYERS = list(range(0, 28, 3))\n",
        "num_layers = model.config.num_hidden_layers\n",
        "DEV = model.device\n",
        "HOP1_RE = re.compile(r'<hop1>(.*?)</hop1>', re.DOTALL | re.IGNORECASE)\n",
        "\n",
        "def build_inputs(prompt, cot_prefix, c0, c1):\n",
        "    full = tokenizer(prompt + cot_prefix, return_tensors='pt').input_ids[0]\n",
        "    p_len = len(tokenizer(prompt, return_tensors='pt').input_ids[0])\n",
        "    enc = tokenizer(cot_prefix, return_offsets_mapping=True, add_special_tokens=False)\n",
        "    if len(full) != p_len + len(enc['input_ids']):\n",
        "        return None\n",
        "    offs = enc['offset_mapping']\n",
        "    ts = next((i for i, (cs, ce) in enumerate(offs) if cs <= c0 < ce), None)\n",
        "    te = next((i for i, (cs, ce) in enumerate(offs) if cs < c1 <= ce), None)\n",
        "    if ts is None or te is None:\n",
        "        return None\n",
        "    return full, p_len, (p_len + ts, p_len + te + 1)\n",
        "\n",
        "def make_store_hook(store, key):\n",
        "    def hook(module, args, output):\n",
        "        h = output[0] if isinstance(output, tuple) else output\n",
        "        store[key] = h[0].detach().clone()\n",
        "        return output\n",
        "    return hook\n",
        "\n",
        "@torch.no_grad()\n",
        "def run_rows(input_ids, P, mask, span, configs):\n",
        "    out = []\n",
        "    for s in range(0, len(configs), BATCH):\n",
        "        chunk = configs[s:s + BATCH]\n",
        "        by_mod = {}\n",
        "        for b, cfg in enumerate(chunk):\n",
        "            for mod, pos, vecs in cfg:\n",
        "                by_mod.setdefault(mod, []).append((b, pos, vecs))\n",
        "        handles, cap = [], {}\n",
        "        for mod, items in by_mod.items():\n",
        "            def hook(module, args, output, items=items):\n",
        "                h = output[0] if isinstance(output, tuple) else output\n",
        "                h = h.clone()\n",
        "                for b, pos, vecs in items:\n",
        "                    h[b, pos.to(h.device), :] = vecs.to(h.device)\n",
        "                return (h,) + tuple(output[1:]) if isinstance(output, tuple) else h\n",
        "            handles.append(mod.register_forward_hook(hook))\n",
        "        for Pl in FEATURE_LAYERS:\n",
        "            def cap_hook(module, args, output, Pl=Pl):\n",
        "                h = output[0] if isinstance(output, tuple) else output\n",
        "                cap[Pl] = h[:, span[0]:span[1], :].float().mean(1).cpu().numpy()\n",
        "            handles.append(model.model.layers[Pl].register_forward_hook(cap_hook))\n",
        "        try:\n",
        "            ids = input_ids.unsqueeze(0).repeat(len(chunk), 1).to(DEV)\n",
        "            hid = model.model(input_ids=ids, use_cache=False).last_hidden_state[:, P - 1:-1]\n",
        "            lp = F.log_softmax(model.lm_head(hid).float(), dim=-1)\n",
        "        finally:\n",
        "            for hd in handles:\n",
        "                hd.remove()\n",
        "        tgt = input_ids[P:].to(lp.device)\n",
        "        lp = lp.gather(2, tgt.view(1, -1, 1).expand(len(chunk), -1, 1)).squeeze(2)\n",
        "        lps = lp[:, mask.to(lp.device)].sum(1).tolist()\n",
        "        for b in range(len(chunk)):\n",
        "            out.append((lps[b], np.stack([cap[Pl][b] for Pl in FEATURE_LAYERS])))\n",
        "    return out\n",
        "\n",
        "ids_list, gaps, recov, F_clean, F_cf, F_entity, F_control, has_control = [], [], [], [], [], [], [], []\n",
        "skipped = {'no_hop1': 0, 'tok_mismatch': 0, 'no_diff': 0, 'no_gap': 0}\n",
        "donor = None\n",
        "d_model = model.config.hidden_size\n",
        "\n",
        "for idx, (clean, cf) in enumerate(tqdm(pairs, desc='Extracting probe features')):\n",
        "    cot = clean['generated_cot']\n",
        "    m = HOP1_RE.search(cot)\n",
        "    if not m:\n",
        "        skipped['no_hop1'] += 1; continue\n",
        "    cot_prefix = cot[:m.end()]\n",
        "    cf_prompt = (clean['prompt'].replace(clean['question'], cf['question'])\n",
        "                 if clean['question'] in clean['prompt'] else cf['prompt'])\n",
        "    bc = build_inputs(clean['prompt'], cot_prefix, m.start(1), m.end(1))\n",
        "    bf = build_inputs(cf_prompt, cot_prefix, m.start(1), m.end(1))\n",
        "    if bc is None or bf is None:\n",
        "        skipped['tok_mismatch'] += 1; continue\n",
        "    c_in, Pc, span_c = bc\n",
        "    f_in, Pf, span_f = bf\n",
        "\n",
        "    sm = difflib.SequenceMatcher(a=c_in[:Pc].tolist(), b=f_in[:Pf].tolist(), autojunk=False)\n",
        "    bl = [(i1, i2, j1, j2) for t, i1, i2, j1, j2 in sm.get_opcodes() if t != 'equal']\n",
        "    if not bl:\n",
        "        skipped['no_diff'] += 1; continue\n",
        "    i1, i2 = min(b[0] for b in bl), max(b[1] for b in bl)\n",
        "    j1, j2 = min(b[2] for b in bl), max(b[3] for b in bl)\n",
        "    if i2 == i1 or j2 == j1:\n",
        "        skipped['no_diff'] += 1; continue\n",
        "    c_pos = torch.tensor([i2 - 1]); f_pos = torch.tensor([j2 - 1])\n",
        "\n",
        "    t_ids = c_in[Pc:]\n",
        "    mask = ~torch.isin(t_ids, torch.cat([c_in[i1:i2], f_in[j1:j2]]))\n",
        "    if mask.sum() == 0:\n",
        "        skipped['no_gap'] += 1; continue\n",
        "\n",
        "    store = {}\n",
        "    hs = [model.model.layers[l].register_forward_hook(make_store_hook(store, l)) for l in range(num_layers)]\n",
        "    try:\n",
        "        (lp_clean, fc), = run_rows(c_in, Pc, mask, span_c, [[]])\n",
        "    finally:\n",
        "        for h in hs:\n",
        "            h.remove()\n",
        "    (lp_cf, ff), = run_rows(f_in, Pf, mask, span_f, [[]])\n",
        "    gap = lp_clean - lp_cf\n",
        "    if gap < MIN_GAP:\n",
        "        skipped['no_gap'] += 1; continue\n",
        "\n",
        "    Ls = model.model.layers\n",
        "    configs = [[(Ls[l], f_pos, store[l][c_pos.to(store[l].device)])] for l in range(num_layers)]\n",
        "    if donor is not None:\n",
        "        configs += [[(Ls[l], f_pos, donor[l])] for l in CONTROL_LAYERS]\n",
        "    res = run_rows(f_in, Pf, mask, span_f, configs)\n",
        "\n",
        "    ids_list.append(str(clean.get('id'))); gaps.append(gap)\n",
        "    recov.append([(res[l][0] - lp_cf) / gap for l in range(num_layers)])\n",
        "    F_clean.append(fc.astype(np.float16)); F_cf.append(ff.astype(np.float16))\n",
        "    F_entity.append(np.stack([res[l][1] for l in range(num_layers)]).astype(np.float16))\n",
        "    if donor is not None:\n",
        "        F_control.append(np.stack([r[1] for r in res[num_layers:]]).astype(np.float16)); has_control.append(True)\n",
        "    else:\n",
        "        F_control.append(np.full((len(CONTROL_LAYERS), len(FEATURE_LAYERS), d_model), np.nan, np.float16)); has_control.append(False)\n",
        "\n",
        "    donor = {l: store[l][c_pos.to(store[l].device)].clone() for l in range(num_layers)}\n",
        "    del store\n",
        "    torch.cuda.empty_cache()\n",
        "\n",
        "n = len(ids_list)\n",
        "print(f'\\nPairs: {len(pairs)} | valid: {n} | skipped: {skipped}')\n",
        "assert n > 0\n",
        "np.savez('probe_features.npz',\n",
        "         ids=np.array(ids_list), gap=np.array(gaps, np.float32), recovery=np.array(recov, np.float32),\n",
        "         F_clean=np.stack(F_clean), F_cf=np.stack(F_cf), F_entity=np.stack(F_entity),\n",
        "         F_control=np.stack(F_control), has_control=np.array(has_control),\n",
        "         feature_layers=np.array(FEATURE_LAYERS), control_layers=np.array(CONTROL_LAYERS))\n",
        "json.dump(skipped, open('probe_features_skipped.json', 'w'))\n",
        "print('Saved probe_features.npz')\n"
    ]
})

# ===== CELL 6: Score probes (no GPU needed, seconds) =====
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ===== CELL 6: Score saved features with the fixed probes (no GPU, seconds) =====\n",
        "\n",
        "import json, joblib\n",
        "import numpy as np\n",
        "from scipy.stats import spearmanr\n",
        "from huggingface_hub import hf_hub_download\n",
        "\n",
        "FEATURES_PATH = 'probe_features.npz'\n",
        "PROBE_LAYERS = [9, 10, 11, 12, 13]\n",
        "REPO = 'AnishRacherla/LinguaFranca-Phase3'\n",
        "PROBE_DIR = '/kaggle/working/fixed_probes'  # use local probes we just trained\n",
        "\n",
        "Z = np.load(FEATURES_PATH)\n",
        "FL = list(Z['feature_layers']); CL = list(Z['control_layers'])\n",
        "ids, recovery, has_ctrl = Z['ids'], Z['recovery'], Z['has_control']\n",
        "n, num_layers = recovery.shape\n",
        "print(f'Loaded features for {n} pairs, feature layers {FL}')\n",
        "\n",
        "def load_probe(P):\n",
        "    import os\n",
        "    local = f'{PROBE_DIR}/hop1_probe_layer{P}.joblib'\n",
        "    if os.path.exists(local):\n",
        "        return joblib.load(local)\n",
        "    return joblib.load(hf_hub_download(REPO, f'probes/hop1_probe_layer{P}.joblib', repo_type='dataset'))\n",
        "\n",
        "def score(probe, X):\n",
        "    shp = X.shape[:-1]\n",
        "    flat = np.nan_to_num(X.reshape(-1, X.shape[-1]).astype(np.float64))\n",
        "    return probe.decision_function(flat).reshape(shp)\n",
        "\n",
        "train_ids = None\n",
        "try:\n",
        "    import os\n",
        "    tid_path = f'{PROBE_DIR}/probe_train_ids.json'\n",
        "    if not os.path.exists(tid_path):\n",
        "        tid_path = hf_hub_download(REPO, 'probes/probe_train_ids.json', repo_type='dataset')\n",
        "    train_ids = set(map(str, json.load(open(tid_path))))\n",
        "except Exception:\n",
        "    print('(no probe_train_ids.json found - reporting all pairs only)')\n",
        "\n",
        "sig = lambda x: 1 / (1 + np.exp(-np.asarray(x)))\n",
        "rng = np.random.default_rng(0)\n",
        "def boot(x, B=2000):\n",
        "    x = np.asarray(x); i = rng.integers(0, len(x), (B, len(x))); mm = x[i].mean(1)\n",
        "    return np.percentile(mm, 2.5), np.percentile(mm, 97.5)\n",
        "\n",
        "S = {}\n",
        "for P in PROBE_LAYERS:\n",
        "    k = FL.index(P)\n",
        "    pr = load_probe(P)\n",
        "    S[P] = {'clean': score(pr, Z['F_clean'][:, k]), 'cf': score(pr, Z['F_cf'][:, k]),\n",
        "            'entity': score(pr, Z['F_entity'][:, :, k]), 'control': score(pr, Z['F_control'][:, :, k])}\n",
        "\n",
        "def analyze(sel, title):\n",
        "    print(f'\\n################ {title}: n = {sel.sum()} ################')\n",
        "    for P in PROBE_LAYERS:\n",
        "        cl, co = S[P]['clean'][sel], S[P]['cf'][sel]\n",
        "        ent, ctl, rec = S[P]['entity'][sel], S[P]['control'][sel], recovery[sel]\n",
        "        hc = has_ctrl[sel]\n",
        "        d = co - cl; lo, hi = boot(d)\n",
        "        ok = sig(cl).mean() < 0.3\n",
        "        print(f'================ Probe @ layer {P} ================')\n",
        "        print(f'SANITY: P(fail) on CLEAN correct hops = {sig(cl).mean():.3f} '\n",
        "              f\"{'OK' if ok else 'TOO HIGH - wrong probe or feature mismatch, do not interpret'}\")\n",
        "        print('TEST A - same hop-1 words, only the question entity differs:')\n",
        "        print(f'  P(fail) clean {sig(cl).mean():.3f} -> corrupted {sig(co).mean():.3f} | '\n",
        "              f'log-odds rise {d.mean():+.2f} [95% CI {lo:+.2f}, {hi:+.2f}] | {(d > 0).mean()*100:.0f}% of pairs rise')\n",
        "        print(f'TEST B - patch the entity at layer L (only L < {P} can reach the probe):')\n",
        "        print(f\"  {'L':>3} | behaviour recovery | probe log-odds drop | shuffled-control drop\")\n",
        "        xs, ys = [], []\n",
        "        for l in range(num_layers):\n",
        "            drop = co - ent[:, l]\n",
        "            cs = f'{(co[hc] - ctl[hc, CL.index(l)]).mean():+.2f}' if l in CL and hc.any() else '   -'\n",
        "            if l < P:\n",
        "                xs += list(rec[:, l]); ys += list(drop)\n",
        "            if l <= P + 1:\n",
        "                print(f'  {l:>3} | {rec[:, l].mean():18.2f} | {drop.mean():+19.2f} | {cs:>21}')\n",
        "        rho, pval = spearmanr(xs, ys)\n",
        "        print(f'  Spearman(behaviour recovery, probe drop) over pairs x layers<{P}: rho = {rho:.2f} (p = {pval:.1e})')\n",
        "\n",
        "analyze(np.ones(n, bool), 'ALL valid pairs')\n",
        "if train_ids is not None:\n",
        "    held = np.array([i not in train_ids for i in ids])\n",
        "    if held.sum() >= 10:\n",
        "        analyze(held, 'HELD-OUT pairs only (probe never trained on them)')\n",
        "    else:\n",
        "        print(f'\\nOnly {held.sum()} held-out pairs - too few for a separate analysis.')\n"
    ]
})

# Build the notebook
nb = {
    "nbformat": 4,
    "nbformat_minor": 4,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        }
    },
    "cells": cells
}

with open("create_kaggle_probe_fix.ipynb", "w") as f:
    json.dump(nb, f, indent=1)

print("Created create_kaggle_probe_fix.ipynb")
